version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'PROJREDES'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  datascience-notebook:
      image:    jupyter/datascience-notebook
      volumes:
        - /home/jorgejr/Documentos/GitHub/Projeto Redes:/home/jovyan/work
        - /home/jorgejr/Documentos/GitHub/Projeto Redes:/home/jovyan/work/datasets
        - /home/jorgejr/Documentos/GitHub/Projeto Redes:/home/jovyan/work/modules
        - /home/jorgejr/Documentos/GitHub/Projeto Redes:/etc/ssl/notebook
      ports:
        - 8891:8888
      container_name:   jupyter_notebook
# Names our volume
volumes:
  my-db: